project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

website:
  title: "My Website"
  navbar:
    right: 
      - resources.qmd
      - text: "Data Viz"
        menu: 
          - text: "Summer Movies"
            href: summermovies.html
          - text: "Campus Pride Index"
            href: pride.html
      - text: "Mini Project 2"
        href: friendsdialogue.html
      - text:  "Mini Project 3"
        href: Project3.html
      - text: "Project 4"
        href: Project4.html
      - text: "Presentation"
        href: Project5.html
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: blue
      dark: solar
    css: styles.css
    toc: true
    page-layout: full


editor: visual


