---
title: "Friends Dialogue"
description: |
  Analysis of Friends Dialogue
author: Mayra Coruh
date: October 2, 2024
format: html
execute:
  warning: false
  message: false
---

```{r}
library(friends)
library(stringr)
library(tidyr)
library(dplyr)
library(ggplot2)
data(friends)
```

# Finding the number of times Rachel says "honey" across all seasons

```{r}
rachel_dialogue <- friends |>
  dplyr::filter(speaker == "Rachel Green") |>
  select(season, text)

rachel_honey_count <- rachel_dialogue |>
  mutate(honey_count = str_count(text, "(?i)\\bhoney\\b"))

honey_by_season <- rachel_honey_count |>
  group_by(season) |> 
  summarise(total_honey = sum(honey_count))

ggplot(honey_by_season, aes(x = season, y = total_honey)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  theme_minimal() +
  labs(
      title = "Number of Times Rachel Says 'Honey' per Season",
       x = "Season",
       y = "Number of 'Honey' Occurrences"
)

```

# Description of Insights 
The histogram illustrates that the use of "honey" fluctuates significantly across seasons, with some seasons showing higher frequencies than others.   

# Analysis of Utterance Categories

```{r}
summary_data <- friends |>
  mutate(text_lower = str_to_lower(text),  
        is_love = str_detect(text_lower, "\\blove\\b"),
        is_question = str_detect(text_lower, "^(what|where|who|when|how)"),
        has_multiple_exclamations = str_detect(text_lower, "!{2,}")
  )

summary_data |>
  summarise(
      love_statements = sum(is_love),
      questions = sum(is_question),
      multiple_exclamations = sum(has_multiple_exclamations)
      ) |>
  pivot_longer(cols = everything(), names_to = "category", values_to = "count")

  total_data = full_join(summary_data, friends, by ="speaker") --> new fata frame that has count and category columns. the problem is that the category is not in summary_data

summary_data |>
  ggplot(aes(x = category, y = count, fill = category)) +
  geom_bar(stat = "identity") +
  labs(title = "Analysis of Utterance Categories", x = "Category", y = "Count") +
  theme_minimal()
```
# Description of Insights 


